feat: REST API для работы с контрагентами
AlKl1M/contractor pull request #1
Opened 2024-07-01 09:02 UTC by AlKl1M

2024-07-04 10:44 UTC, gobaz095 requested changes
Подключи пожалуйста сваггер
https://habr.com/ru/articles/541592/
https://www.baeldung.com/swagger-2-documentation-for-spring-rest-api

А также сделай документацию openapi для своих контроллеров, дто и прочего:
https://www.baeldung.com/spring-rest-openapi-documentation
https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations

2024-07-08 15:26 UTC, gobaz095 requested changes
Еще хочу Assert.Throws, раз эксепшены свои есть:)

2024-07-08 15:26 UTC, gobaz095 commented on src/main/java/com/alkl1m/contractor/repository/jdbc/ContractorJdbcRepository.java
> +        List<Contractor> contractors = jdbcTemplate.query(queryBuilder.toString(), new ContractorRowMapper());
Так не надо делать:) Пихать все в запрос. Пишем через именованные параметры запроса, при помощи Map<String, Object> или MapSqlParameterSource
Подробнее:
https://stackoverflow.com/questions/4333015/does-the-preparedstatement-avoid-sql-injection
https://habr.com/ru/articles/725134/

2024-07-08 15:26 UTC, gobaz095 commented on src/main/java/com/alkl1m/contractor/service/impl/ContractorServiceImpl.java
> +        existingContractor.setModifyUserId("1");
Используй переменную, чтобы везде не писать "1" вместо юзера, пока не откуда брать юзера. И лучше что то осмысленное, типа defaultUser

2024-07-08 15:26 UTC, gobaz095 commented on src/main/java/com/alkl1m/contractor/service/impl/ContractorServiceImpl.java
> +    private Contractor updateExistingContractor(NewContractorPayload payload, Contractor existingContractor, Country country, Industry industry, OrgForm orgForm) {
Зачем вытягивать зарнее эти параметры и их передавать сюда? Передай пейлоад целиком, вытяни тут же. У тебя же он используется.

2024-07-08 17:15 UTC, AlKl1M commented on src/main/java/com/alkl1m/contractor/service/impl/ContractorServiceImpl.java
> +    private Contractor updateExistingContractor(NewContractorPayload payload, Contractor existingContractor, Country country, Industry industry, OrgForm orgForm) {
https://github.com/AlKl1M/contractor/pull/1/commits/ff2db45bc371228b1331788b181d245805630f8a

2024-07-08 17:15 UTC, AlKl1M commented on src/main/java/com/alkl1m/contractor/service/impl/ContractorServiceImpl.java
> +        existingContractor.setModifyUserId("1");
https://github.com/AlKl1M/contractor/pull/1/commits/814873812340204234149abeb3529072a750d5f7

2024-07-08 17:15 UTC, AlKl1M commented on src/main/java/com/alkl1m/contractor/repository/jdbc/ContractorJdbcRepository.java
> +        List<Contractor> contractors = jdbcTemplate.query(queryBuilder.toString(), new ContractorRowMapper());
https://github.com/AlKl1M/contractor/pull/1/commits/aa4d3fd356caca45cb55e219f7ff41f5f293afd4 https://github.com/AlKl1M/contractor/pull/1/commits/d9f6cc523b4662c68d5118ef9e30688fe7b89194

2024-07-08 17:24 UTC, AlKl1M commented on src/main/java/com/alkl1m/contractor/repository/jdbc/ContractorJdbcRepository.java
> +        List<Contractor> contractors = jdbcTemplate.query(queryBuilder.toString(), new ContractorRowMapper());
https://github.com/AlKl1M/contractor/pull/1/commits/7b1c1d31f5514b6f0e16a31ee231ff92feaa6749

2024-07-09 11:19 UTC, merged